
services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html

  wordpress:
    container_name: wp-php
    build: requirements/wordpress/.
    image: wordpress
    volumes:
      - ./web:/var/www/html
